language: node_js
node_js:
- '0.10'
- '0.11'
script:
- npm run build
- npm run documentation
cache:
  directories:
  - node_modules
notifications:
  email: false
  irc: chat.freenode.net#canon-dev
sudo: false
